services:
  playground:
    build: .
    ports:
      - 5000:5000
    networks:
      - playground
    depends_on:
      - rabbit
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 100M

  rabbit:
    image: rabbitmq:4.1.0-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - playground
    deploy:
      resources:
        limits:
          memory: 1000M
        reservations:
          memory: 500M

  elasticsearch:
    image: elasticsearch:9.0.1
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=false
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ES_JAVA_OPTS='-Xmx1g -Xms1g'
    deploy:
      resources:
        limits:
          memory: 1000M

  kibana:
    image: docker.elastic.co/kibana/kibana:9.0.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTICSEARCH_SERVICE_TOKEN=${ELASTICSEARCH_SERVICE_TOKEN}
    ports:
      - 5601:5601
    deploy:
      resources:
        limits:
          memory: 500M

  prometheus:
    image: prom/prometheus:v3.3.1
    ports:
      - 9090:9090
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    deploy:
      resources:
        limits:
          memory: 500M

  grafana:
    image: grafana/grafana-oss:12.0.0
    restart: unless-stopped
    ports:
     - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    deploy:
      resources:
        limits:
          memory: 500M

  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    command: start
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres
    networks:
      - keycloak_network
      - playground

networks:
  playground: {}
  keycloak_network: {}
